/**
 * No shebang here: vite.config.ts imports this file, and esbuild refuses to
 * parse a shebang when loading a config dependency.
 *
 * Generates dist/sw.js after a build.
 *
 * The precache list is read off the finished dist/ rather than guessed, because
 * the asset filenames are content-hashed and a hand-maintained list would be
 * wrong the first time anyone changed a stylesheet. The cache name is the build
 * id, so a new deploy cannot reuse an old cache and there is no way to end up
 * serving last week's bundle forever, which is the failure mode that makes
 * people distrust offline apps.
 *
 * Run by the build, not separately: a service worker generated from a different
 * dist/ than the one being served is worse than none.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const DIST = path.resolve('dist');
const BASE = '/lantern/';

/** Everything worth having when there is no signal. */
function collect(dir, prefix = '') {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...collect(full, `${prefix}${entry}/`));
    } else {
      out.push(`${prefix}${entry}`);
    }
  }
  return out;
}

export function writeServiceWorker() {
  const files = collect(DIST)
    // version.json is how the app notices a NEW build exists. Precaching it
    // would mean the check compares the running build against a copy of
    // itself, and the app could never discover an update again.
    .filter((f) => f !== 'version.json' && f !== 'sw.js')
    .map((f) => BASE + f);

  const shell = `${BASE}index.html`;
  const precache = [...new Set([BASE, shell, ...files])];

  const buildId = JSON.parse(
    readFileSync(path.join(DIST, 'version.json'), 'utf8'),
  ).id;

  const sw = `/* Generated by scripts/sw.mjs. Do not edit dist/sw.js by hand. */
const CACHE = ${JSON.stringify(`lantern-${buildId}`)};
const SHELL = ${JSON.stringify(shell)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      await cache.addAll(PRECACHE);
      // Take over straight away. Waiting for every tab to close is the polite
      // pattern and it deadlocks an installed home-screen app, which is never
      // closed properly and would keep the old worker alive indefinitely.
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key !== CACHE) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

/**
 * Ignore Vary on every lookup.
 *
 * The preview server answers static assets with a Vary: Origin header, and a
 * module script tagged crossorigin sends an Origin header that the precache
 * request did not. The cached bytes are identical; the Vary check still fails,
 * the lookup misses, and the app is dead offline while every URL sits in the
 * cache looking correct. These are content-hashed static files, so no request
 * header can change what the right answer is.
 */
const MATCH = { ignoreVary: true };

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Never from cache first. This file is the only way the app learns that a
  // newer build exists, so a cached copy would pin it to the running version.
  if (url.pathname.endsWith('/version.json')) {
    event.respondWith(
      fetch(req).catch(async () => (await caches.match(req, MATCH)) || Response.error()),
    );
    return;
  }

  // One page, so every navigation is the same shell.
  if (req.mode === 'navigate') {
    event.respondWith((async () => (await caches.match(SHELL, MATCH)) || fetch(req))());
    return;
  }

  event.respondWith(
    (async () => {
      const hit = await caches.match(req, MATCH);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok && res.type === 'basic') {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone());
      }
      return res;
    })(),
  );
});
`;

  writeFileSync(path.join(DIST, 'sw.js'), sw, 'utf8');
  return { files: precache.length, buildId };
}
